[package]
name = "locusdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glommio = "0.9.0"
bumpalo = "3.15.0"
rand = "0.8.5"

[profile.release]
codegen-units = 1
lto = "fat"
